# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 128bed7a171b4ab3e2efcf345a843fc886cc1f11783bd6c2ce7c2fac0590a9ffcb388bc581aa74049db6ddf5f8c471b85c8416c3d825e6e682b02f36d456aa16

test:
  secret_key_base: c40f5a5b24da027243a213fa46050a9600853f12f7b91b85ced8524829a1d0db821a15cdb251750f53d703da661a4af9164fd24043daa998c293ef9a9164373b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
